# Establece la imagen base
FROM node:16-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json (si existe) al directorio de trabajo
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia todo el código fuente al directorio de trabajo
COPY . .

# Construye la aplicación de React
RUN npm run build

# Configura un servidor web ligero para servir la aplicación de React
FROM nginx:alpine

# Copia los archivos generados en el paso anterior al directorio de Nginx
COPY --from=0 /app/build /usr/share/nginx/html

# Expone el puerto en el que se ejecuta Nginx
EXPOSE 80

# Define el comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]